name: iOS Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter iOS
        run: flutter build ios --no-codesign

      - name: Archive iOS App
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $PWD/build/Runner.xcarchive

      - name: Create IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ios/build/Runner.xcarchive \
            -exportPath ios/build/ipa \
            -exportOptionsPlist ios/Runner/Info.plist

      - name: List Build Directory
        run: ls -R ios/build/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app.ipa
          path: ios/build/ipa/*.ipa